// Codegen + drift detection tests for catalog ↔ markdown sync.
// Catalog source-of-truth = crates/axhub-helpers/data/catalog.json (Rust).

import { describe, expect, test } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

import { formatEntry, sortKeys } from "../scripts/codegen-catalog";

interface ErrorEntry {
  emotion: string;
  cause: string;
  action: string;
  button?: string;
}

const REPO_ROOT = join(import.meta.dir, "..");
const CATALOG_JSON = join(REPO_ROOT, "crates/axhub-helpers/data/catalog.json");
const HAND_WRITTEN = join(REPO_ROOT, "skills/deploy/references/error-empathy-catalog.md");
const GENERATED = join(REPO_ROOT, "skills/deploy/references/error-empathy-catalog.generated.md");

const CATALOG: Record<string, ErrorEntry> = JSON.parse(readFileSync(CATALOG_JSON, "utf8"));

describe("catalog → markdown codegen", () => {
  test("generated markdown file exists", () => {
    expect(existsSync(GENERATED)).toBe(true);
  });

  test("generated markdown starts with auto-generated header", () => {
    const content = readFileSync(GENERATED, "utf8");
    expect(content).toMatch(/^<!-- AUTO-GENERATED by scripts\/codegen-catalog\.ts/);
  });

  test("generated markdown contains every catalog key", () => {
    const content = readFileSync(GENERATED, "utf8");
    for (const key of Object.keys(CATALOG)) {
      const headingPattern = key.includes(":")
        ? `### exit ${key}`
        : `## exit ${key}`;
      expect(content).toContain(headingPattern);
    }
  });

  test("generated markdown 4-part schema present per entry", () => {
    const content = readFileSync(GENERATED, "utf8");
    const entries = Object.entries(CATALOG);
    for (const [key, entry] of entries) {
      const headingPattern = key.includes(":")
        ? `### exit ${key}`
        : `## exit ${key}`;
      const idx = content.indexOf(headingPattern);
      expect(idx).toBeGreaterThan(-1);
      const section = content.slice(idx, idx + 2000);
      expect(section).toContain("**감정:**");
      expect(section).toContain("**원인:**");
      expect(section).toContain("**해결:**");
      if (entry.button !== undefined) {
        expect(section).toContain("**버튼:**");
      }
    }
  });

  test("idempotency: re-running formatEntry on each entry produces identical output", () => {
    const keys = sortKeys(Object.keys(CATALOG));
    const first = keys.map((k) => formatEntry(k, CATALOG[k]!)).join("");
    const second = keys.map((k) => formatEntry(k, CATALOG[k]!)).join("");
    expect(first).toBe(second);
  });
});

describe("catalog ↔ hand-written markdown drift detection", () => {
  test("hand-written markdown exists", () => {
    expect(existsSync(HAND_WRITTEN)).toBe(true);
  });

  test("every catalog key has a corresponding section in hand-written markdown", () => {
    const content = readFileSync(HAND_WRITTEN, "utf8");
    const missing: string[] = [];
    for (const key of Object.keys(CATALOG)) {
      if (key.includes(":")) {
        const [exitCode, errorCode] = key.split(":");
        const hasExitWithErrorCode = content.includes(`exit ${exitCode}`) && content.includes(errorCode!);
        if (!hasExitWithErrorCode) missing.push(key);
      } else {
        if (!content.includes(`exit ${key}`)) missing.push(key);
      }
    }
    expect(missing).toEqual([]);
  });

  test("hand-written markdown contains the 4-part labels (감정/원인/해결/버튼)", () => {
    const content = readFileSync(HAND_WRITTEN, "utf8");
    expect(content).toContain("**감정:**");
    expect(content).toContain("**원인:**");
    expect(content).toContain("**해결:**");
    expect(content).toContain("**버튼:**");
  });
});
