// Phase 3 US-202: codegen + drift detection tests for catalog ↔ markdown sync.

import { describe, expect, test } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

import { CATALOG } from "../src/axhub-helpers/catalog";
import { formatEntry, sortKeys } from "../scripts/codegen-catalog";

const REPO_ROOT = join(import.meta.dir, "..");
const HAND_WRITTEN = join(REPO_ROOT, "skills/deploy/references/error-empathy-catalog.md");
const GENERATED = join(REPO_ROOT, "skills/deploy/references/error-empathy-catalog.generated.md");

describe("catalog → markdown codegen (US-202)", () => {
  test("generated markdown file exists", () => {
    expect(existsSync(GENERATED)).toBe(true);
  });

  test("generated markdown starts with auto-generated header", () => {
    const content = readFileSync(GENERATED, "utf8");
    expect(content).toMatch(/^<!-- AUTO-GENERATED by scripts\/codegen-catalog\.ts/);
  });

  test("generated markdown contains every catalog key", () => {
    const content = readFileSync(GENERATED, "utf8");
    for (const key of Object.keys(CATALOG)) {
      // Each key appears as `## exit N` or `### exit N:code`
      const headingPattern = key.includes(":")
        ? `### exit ${key}`
        : `## exit ${key}`;
      expect(content).toContain(headingPattern);
    }
  });

  test("generated markdown 4-part schema present per entry", () => {
    const content = readFileSync(GENERATED, "utf8");
    const entries = Object.entries(CATALOG);
    for (const [key, entry] of entries) {
      // Split on heading to get this entry's section
      const headingPattern = key.includes(":")
        ? `### exit ${key}`
        : `## exit ${key}`;
      const idx = content.indexOf(headingPattern);
      expect(idx).toBeGreaterThan(-1);
      const section = content.slice(idx, idx + 2000);
      expect(section).toContain("**감정:**");
      expect(section).toContain("**원인:**");
      expect(section).toContain("**해결:**");
      if (entry.button !== undefined) {
        expect(section).toContain("**버튼:**");
      }
    }
  });

  test("idempotency: re-running formatEntry on each entry produces identical output", () => {
    // Pure-function test (no fs): re-format every entry, compare byte-for-byte.
    const keys = sortKeys(Object.keys(CATALOG));
    const first = keys.map((k) => formatEntry(k, CATALOG[k]!)).join("");
    const second = keys.map((k) => formatEntry(k, CATALOG[k]!)).join("");
    expect(first).toBe(second);
  });
});

describe("catalog ↔ hand-written markdown drift detection (US-202)", () => {
  test("hand-written markdown exists", () => {
    expect(existsSync(HAND_WRITTEN)).toBe(true);
  });

  test("every catalog.ts key has a corresponding section in hand-written markdown", () => {
    const content = readFileSync(HAND_WRITTEN, "utf8");
    const missing: string[] = [];
    for (const key of Object.keys(CATALOG)) {
      if (key.includes(":")) {
        // Sub-classified keys may be rendered as `exit 64 + \`validation.X\``
        // (markdown style) or `exit 64:validation.X` (machine style). Match
        // either by checking both the exit code AND the error code substring.
        const [exitCode, errorCode] = key.split(":");
        const hasExitWithErrorCode = content.includes(`exit ${exitCode}`) && content.includes(errorCode!);
        if (!hasExitWithErrorCode) missing.push(key);
      } else {
        if (!content.includes(`exit ${key}`)) missing.push(key);
      }
    }
    expect(missing).toEqual([]);
  });

  test("hand-written markdown contains the 4-part labels (감정/원인/해결/버튼)", () => {
    const content = readFileSync(HAND_WRITTEN, "utf8");
    expect(content).toContain("**감정:**");
    expect(content).toContain("**원인:**");
    expect(content).toContain("**해결:**");
    expect(content).toContain("**버튼:**");
  });
});
