import { describe, expect, test } from "bun:test";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

// Phase 2 — SDK knowledge pack INTEGRITY gate. Packs are generated by the SDK
// repo's scripts/gen-sdk-distill.py and vendored here. This catches a missing /
// hand-mangled pack, or a pack whose stamped sha drifts from the committed
// PINNED_SDK.json — never silently feeding the expert wrong API knowledge.
// It is NOT an SDK-staleness gate: the pack sha and PINNED are co-generated from
// the same git_sha() call, so "SDK moved forward, packs stale" detection needs
// the live SDK HEAD at CI time — impossible while the SDK repo has no remote
// (tracked as a PR follow-up).

const REPO_ROOT = join(import.meta.dir, "..");
const PACK_DIR = join(REPO_ROOT, "skills/migrate/sdk-knowledge");
const LANGS = ["go", "java", "kotlin", "node", "python", "ruby"];

const read = (name: string): string => readFileSync(join(PACK_DIR, name), "utf8");

const frontmatter = (md: string): Record<string, string> => {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  const out: Record<string, string> = {};
  if (m) {
    for (const line of m[1].split("\n")) {
      const i = line.indexOf(":");
      if (i > 0) out[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
  }
  return out;
};

interface Pinned {
  route_surface_sha: string;
  conformance_baseline: string;
  languages: Record<string, { source_sha: string; sdk_version: string }>;
}
const pinned = JSON.parse(read("PINNED_SDK.json")) as Pinned;

// Per-language canonical client-construction invariants. These mirror
// render_wrapper_preview in crates/axhub-helpers/src/migrate_plan.rs — the
// wrapper seed of truth. If the helper's wrapper changes, regenerate the packs
// and update these tokens together (the byte-exact regen cross-check lands with
// the agent-drift test in Phase 3).
// node omits base_url (relies on the SDK default); the typed-init languages pin
// "https://api.axhub.ai" — included so a base_url change in the helper's
// render_wrapper_preview that doesn't reach the packs fails the cross-drift pair.
const WRAPPER_TOKENS: Record<string, string[]> = {
  node: ["new AxHubClient(", "tokenType: 'pat'", "AX_HUB_PAT", "defaultTenantId"],
  python: ["AxHubClient(", "token_type=TokenType.PAT", "AXHUB_TOKEN", "default_tenant_id", "https://api.axhub.ai"],
  go: ["axhub.NewClient(", "TokenTypePAT", "AXHUB_TOKEN", "DefaultTenantID", "https://api.axhub.ai"],
  ruby: ["AxHub::Client.new(", "token_type: :pat", "AXHUB_TOKEN", "default_tenant_id", "https://api.axhub.ai"],
  java: ["AxHubClient.builder()", ".tokenType(TokenType.PAT)", "AXHUB_TOKEN", ".defaultTenantId(", "https://api.axhub.ai"],
  kotlin: ["AxHubKotlinClient(", "tokenType = TokenType.PAT", "AXHUB_TOKEN", "defaultTenantId =", "https://api.axhub.ai"],
};

describe("SDK knowledge pack freshness + integrity", () => {
  test("ships exactly one pack per supported language", () => {
    const files = readdirSync(PACK_DIR)
      .filter((f) => f.endsWith(".md"))
      .sort();
    expect(files).toEqual(LANGS.map((l) => `${l}.md`).sort());
  });

  test("PINNED_SDK.json covers route surface + every language", () => {
    expect(pinned.route_surface_sha).toMatch(/^[0-9a-f]{40}$/);
    expect(pinned.conformance_baseline).toBeTruthy();
    for (const lang of LANGS) {
      expect(pinned.languages[lang]?.source_sha).toMatch(/^[0-9a-f]{40}$/);
    }
  });

  for (const lang of LANGS) {
    test(`${lang}: version parseable + sha matches the committed pin`, () => {
      const fm = frontmatter(read(`${lang}.md`));
      expect(fm.lang).toBe(lang);
      // non-empty parseable version — a stale/unpinned pack fails loud
      expect(fm.sdk_version).toMatch(/^\d+\.\d+\.\d+$/);
      expect(fm.source_sha).toMatch(/^[0-9a-f]{40}$/);
      // pack-integrity: pack stamp must equal the committed manifest (catches a
      // hand-edited or divergent pack; not SDK staleness — see file header).
      expect(fm.source_sha).toBe(pinned.languages[lang].source_sha);
      expect(fm.sdk_version).toBe(pinned.languages[lang].sdk_version);
    });

    test(`${lang}: §1 carries the canonical wrapper (hallucination guard)`, () => {
      const md = read(`${lang}.md`);
      const clientInit = md.slice(md.indexOf("## 1. Client init"), md.indexOf("## 2. Auth"));
      expect(clientInit.length).toBeGreaterThan(0);
      for (const tok of WRAPPER_TOKENS[lang]) {
        expect(clientInit).toContain(tok);
      }
    });

    test(`${lang}: carries auth mapping + conformance baseline`, () => {
      const md = read(`${lang}.md`);
      expect(md).toContain("X-Api-Key"); // PAT
      expect(md).toContain("Authorization: Bearer"); // JWT
      expect(md).toContain("oauth-token-form-urlencoded"); // a systemic contract id
      expect(md).toContain(pinned.conformance_baseline);
    });
  }
});
