import { describe, expect, test } from "bun:test";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

// SDK knowledge pack INTEGRITY gate. Packs are generated by the SDK repo's
// scripts/gen-sdk-distill.py and vendored here. The pack source_sha and
// PINNED_SDK.json both stamp from the committed PINNED_SDK.lock.json (Item 1A) —
// the deliberate human pin. The distiller asserts each SDK repo HEAD == the lock
// before emitting, so generation against an unpinned SDK checkout fails loud
// instead of silently vendoring a mismatched pack. This catches a missing /
// hand-mangled / sha-tampered pack and a pack diverging from the lock.
// Honest limitation: it does NOT detect a regen skipped entirely — lock and
// packs then stay stale together (lockstep). That needs a remote + CI on the
// SDK repo (item 1B, deferred).

const REPO_ROOT = join(import.meta.dir, "..");
const PACK_DIR = join(REPO_ROOT, "skills/migrate/sdk-knowledge");
const LANGS = ["go", "java", "kotlin", "node", "python", "ruby"];

const read = (name: string): string => readFileSync(join(PACK_DIR, name), "utf8");

const frontmatter = (md: string): Record<string, string> => {
  const m = md.match(/^---\n([\s\S]*?)\n---/);
  const out: Record<string, string> = {};
  if (m) {
    for (const line of m[1].split("\n")) {
      const i = line.indexOf(":");
      if (i > 0) out[line.slice(0, i).trim()] = line.slice(i + 1).trim();
    }
  }
  return out;
};

interface Pinned {
  route_surface_sha: string;
  conformance_baseline: string;
  languages: Record<string, { source_sha: string; sdk_version: string }>;
}
const pinned = JSON.parse(read("PINNED_SDK.json")) as Pinned;
const lock = JSON.parse(read("PINNED_SDK.lock.json")) as Pinned;

describe("SDK knowledge pack freshness + integrity", () => {
  test("ships exactly one pack per supported language", () => {
    const files = readdirSync(PACK_DIR)
      .filter((f) => f.endsWith(".md"))
      .sort();
    expect(files).toEqual(LANGS.map((l) => `${l}.md`).sort());
  });

  test("PINNED_SDK.json covers route surface + every language", () => {
    expect(pinned.route_surface_sha).toMatch(/^[0-9a-f]{40}$/);
    expect(pinned.conformance_baseline).toBeTruthy();
    for (const lang of LANGS) {
      expect(pinned.languages[lang]?.source_sha).toMatch(/^[0-9a-f]{40}$/);
    }
  });

  test("PINNED_SDK.lock.json is the committed pin covering every language", () => {
    expect(lock.route_surface_sha).toMatch(/^[0-9a-f]{40}$/);
    for (const lang of LANGS) {
      expect(lock.languages[lang]?.source_sha).toMatch(/^[0-9a-f]{40}$/);
      expect(lock.languages[lang]?.sdk_version).toMatch(/^\d+\.\d+\.\d+$/);
    }
  });

  for (const lang of LANGS) {
    test(`${lang}: version parseable + sha matches the committed pin`, () => {
      const fm = frontmatter(read(`${lang}.md`));
      expect(fm.lang).toBe(lang);
      // non-empty parseable version — a stale/unpinned pack fails loud
      expect(fm.sdk_version).toMatch(/^\d+\.\d+\.\d+$/);
      expect(fm.source_sha).toMatch(/^[0-9a-f]{40}$/);
      // non-tautological: pack AND PINNED both stamp from the committed lock (the
      // deliberate human pin), so this compares the vendored state against an
      // independent committed reference — a pack/sha divergence fails here, and a
      // generation against an off-pin SDK fails earlier in the distiller.
      expect(fm.source_sha).toBe(lock.languages[lang].source_sha);
      expect(fm.sdk_version).toBe(lock.languages[lang].sdk_version);
      expect(pinned.languages[lang].source_sha).toBe(lock.languages[lang].source_sha);
    });

    test(`${lang}: §1 client init block present`, () => {
      // Full-body equality vs render_wrapper_preview is asserted in the Rust test
      // pack_client_init_equals_render_wrapper_preview_full_body (it has both the
      // seed and the pack). Here just assert the §1 block exists and is non-trivial.
      const md = read(`${lang}.md`);
      const clientInit = md.slice(md.indexOf("## 1. Client init"), md.indexOf("## 2. Auth"));
      expect(clientInit).toContain("## 1. Client init");
      expect(clientInit.length).toBeGreaterThan(50);
    });

    test(`${lang}: carries auth mapping + conformance baseline`, () => {
      const md = read(`${lang}.md`);
      expect(md).toContain("X-Api-Key"); // PAT
      expect(md).toContain("Authorization: Bearer"); // JWT
      expect(md).toContain("oauth-token-form-urlencoded"); // a systemic contract id
      expect(md).toContain(pinned.conformance_baseline);
    });

    test(`${lang}: carries the §6 data-operation surface (schemaless)`, () => {
      const md = read(`${lang}.md`);
      expect(md).toContain("## 6. Data operations");
      expect(md).toContain("schemaless"); // rows are schemaless, not typed bodies
      expect(md).toContain("client.data"); // the data facade pattern
      expect(md).toContain("page"); // list query vocabulary
    });
  }
});
