import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dir, "..");
const readRepo = (path: string): string => readFileSync(join(REPO_ROOT, path), "utf8");

describe("update Desktop UX contract", () => {
  test("plugin manifest preserves update no-preamble routing contract", () => {
    const manifest = JSON.parse(readRepo(".claude-plugin/plugin.json")) as { description: string };
    const marketplace = JSON.parse(readRepo(".claude-plugin/marketplace.json")) as { plugins: Array<{ description: string }> };
    const descriptions = [manifest.description, marketplace.plugins[0]?.description ?? ""];

    expect(manifest.description).toContain("Natural-language axhub requests should route to one of onboarding/bootstrap/deploy/import/development/diagnosis/update");
    expect(manifest.description).toContain("clarity is manual/explicit-only");
    for (const description of descriptions) {
      expect(description).toContain("Import priority is strict");
      expect(description).toContain("existing app/local folder");
      expect(description).toContain("작업 폴더는");
      expect(description).toContain("invoke the axhub import skill before generic Code-mode folder inspection");
      expect(description).toContain("The first visible import text should start exactly `기존 앱을 axhub에 가져올 준비를 확인할게요.`");
    }
    expect(manifest.description).toContain("axhub가 진짜 최신인지 먼저 확인해주고");
    expect(manifest.description).toContain("General helper-role phrasing without freshness words must not invoke update");
    expect(manifest.description).toContain("Routing priority is strict");
    expect(manifest.description).toContain("invoke the axhub update skill first");
    expect(manifest.description).toContain("first visible assistant text is exactly `현재 버전을 확인할게요.`");
    expect(manifest.description).toContain("ordinary Code-mode shell work");
    expect(manifest.description).toContain("Never start freshness prompts with `Using /axhub:clarity`");
    expect(manifest.description).toContain("run scripts, shell/version probes, app-status tools");
    expect(manifest.description).toContain("Claude Desktop axhub App/MCP tools");
    expect(manifest.description).toContain("unrelated plugin mode");
    expect(manifest.description).toContain("/oh-my-claudecode:autopilot");
    expect(manifest.description).toContain("exact `axhub apps --help` then `axhub apps list --json`");
    expect(manifest.description).toContain("plugin lookup uses exact `claude plugin list`, never `claude plugin list 2>&1`");
    expect(manifest.description).toContain("once the remaining app-status flow begins, do not rerun command-v");
    expect(manifest.description).toContain("never `command -v axhub && axhub --version`");
    expect(manifest.description).toContain("never `command -v claude && claude plugin list`");
    expect(manifest.description).toContain("never `claude plugin list 2>&1 | grep`");
    expect(manifest.description).toContain("when folder/current conversation/latest list clearly identifies a related app");
    expect(manifest.description).toContain("do not ask which app");
    expect(manifest.description).toContain("before any summary");
    expect(manifest.description).toContain("`axhub apps get <app> --json`");
    expect(manifest.description).toContain("`axhub deploy list --app <app> --json`");
    expect(manifest.description).toContain("nonexistent `axhub app list`");
    expect(manifest.description).toContain("never `axhub deployment list`");
    expect(manifest.description).toContain("never Claude Desktop axhub App/MCP permission popups");
    expect(manifest.description).toContain("never &&, pipes, redirects, grep, or head");
  });

  test("does not read plugin cache manifests in Claude Desktop", () => {
    const update = readRepo("skills/update/SKILL.md");

    expect(update).toContain("description: 'axhub 최신 확인, 버전 확인, 업데이트 전용 skill");
    expect(update).toContain("axhub가 진짜 최신인지 먼저 확인");
    expect(update).toContain('일반 UX 역할 문구나 "알아서 진행"만으로는 update 가 아니며');
    expect(update).toContain("freshness/update 단어가 없는 기존 앱 import·배포 요청은 import/deploy 로 양보해요");
    expect(update).not.toContain("명령어는 잘 몰라");
    expect(update).not.toContain("명령어를 잘 모르는");
    expect(update).toContain("일반 Code-mode script");
    expect(update).toContain("/oh-my-claudecode:autopilot");
    expect(update).toContain('첫 visible assistant text는 정확히 "현재 버전을 확인할게요."');
    expect(update).toContain("사용자에게 보이는 첫 문장은 반드시 정확히 `현재 버전을 확인할게요.`");
    expect(update).toContain("app status, app creation, deployment 는 update 뒤에 이어서 처리해요");
    expect(update).toContain("내 앱들이 지금 어떤 상태인지도 알아서 봐줘");
    expect(update).toContain("새 재즈 댄스 수업 예약 앱 하나 만들어서 실제로 배포까지");
    expect(update).toContain("axhub가 진짜 최신인지 먼저 확인해주고, 내 앱들이 지금 어떤 상태인지도 알아서 봐줘");
    expect(update).toContain("Claude Desktop 에서는 `${CLAUDE_PLUGIN_ROOT}/.claude-plugin/plugin.json` 같은 플러그인 캐시 파일을 읽지 않아요");
    expect(update).toContain("스킬 호출 전 사전 안내 문장도 쓰지 않아요");
    expect(update).toContain("작업 디렉토리 밖이라 초보자에게 불필요한 읽기 권한 팝업이 떠요");
    expect(update).toContain("정확히 `claude plugin list` 만 실행한 출력");
    expect(update).toContain("이 권한 카드의 Desktop-visible command 는 글자 하나도 더하지 말고 정확히 `claude plugin list` 예요");
    expect(update).toContain("`command -v claude && claude plugin list`");
    expect(update).toContain("`claude plugin list 2>&1`");
    expect(update).toContain("`claude plugin list 2>&1 | grep ...`");
    expect(update).toContain("redirect");
    expect(update).toContain("실행하려는 command 가 `claude plugin list 2>&1` 또는 `command -v claude && claude plugin list` 로 떠오르면 **반드시 `claude plugin list` 로 바꿔요.**");
    expect(update).toContain("플러그인 버전, 설치 scope, 다음 CLI 확인을 영어 내부 로그처럼 chat 에 쓰지 말고");
    expect(update).toContain("필요한 경우 `현재 플러그인 버전을 확인했어요.` 라고만 말해요");
    expect(update).toContain("버전과 설치 위치를 같은 문장에 섞지 않아요");
    expect(update).toContain("설치 위치값은 업데이트 명령의 `--scope` 인자에만 쓰고 chat 에는 쓰지 않아요");
    expect(update).toContain("플러그인 확인 직후에는 `현재 플러그인 버전을 확인했어요.` 만 보여줘요");
    expect(update).toContain("출력이 길어도 전체 `claude plugin list` 결과를 도구 응답에서 내부적으로 읽고");
    expect(update).toContain("파일 읽기 도구를 쓰지 않아요");
    expect(update).toContain("정확히 `claude plugin list` 한 번으로 `axhub@axhub` 의 현재 버전을 내부 변수 `<PLUGIN_VERSION>` 으로만 둬요");
    expect(update).toContain("`claude plugin list` 가 실패하거나 목록에서 못 찾으면 `<PLUGIN_VERSION>` 없이 CLI 업데이트 확인만 진행해요");
    expect(update).toContain("scope 원문, 영어 진행 로그는 사용자에게 말하지 않아요");
  });

  test("uses the newest enabled plugin entry when Claude lists duplicates", () => {
    const update = readRepo("skills/update/SKILL.md");

    expect(update).toContain("`claude plugin list` 에 `axhub@axhub` 가 여러 번 나오면");
    expect(update).toContain("enabled 항목 중 **가장 높은 semver** 를 `<PLUGIN_VERSION>` 으로 삼아요");
    expect(update).toContain("`local` → `project` → `user`");
    expect(update).toContain("낮은 버전이 함께 남아 있어도 사용자에게 중복 설치·scope 원문을 설명하지 않고");
    expect(update).toContain("성공하면 `claude plugin list` 를 한 번 더 실행해");
    expect(update).toContain("확인된 받은 버전이 CLI 응답의 플러그인 최신 버전보다 높아도 최종 카드에는 확인된 받은 버전만 한국어 결과 줄로 써요");
    expect(update).toContain("낡은 중복 항목을 나열하지 않아요");
    expect(update).toContain("중복 설치 판정 알고리즘");
    expect(update).toContain("낮은 버전 block 이 남아 있어도 그것은 cleanup 대상이 아니며");
    expect(update).toContain("현재 확인한 최고 enabled 버전이 CLI 응답의 플러그인 최신 버전 이상이면 업데이트 필요처럼 보여도");
    expect(update).toContain("`local 1.8.2` 와 `user 1.8.0` 이 함께 있으면 현재 버전은 `1.8.2`");
    expect(update).toContain("`user 1.8.0 → 1.8.2` 같은 정리성 업데이트나 결과 카드를 만들지 않아요");
    expect(update).toContain("이때 낮은 중복 scope 가 있어도 `claude plugin update` 를 실행하지 않아요");
    expect(update).toContain("그 최고 버전을 가진 block 들 안에서만");
    expect(update).toContain("최고 enabled 버전이 이미 최신이면, 낮은 중복 항목을 최신화하기 위한 `claude plugin update` 를 실행하지 않아요");
    expect(update).toContain("NEVER `claude plugin list` 에서 처음 발견한 낡은 `axhub@axhub` 항목만 보고 업데이트 여부를 판단하지 말아요");
    expect(update).toContain("NEVER 최고 enabled semver 가 이미 최신인데도 낮은 중복 scope 를 기준으로");
  });

  test("keeps plugin update confirmation text human-facing", () => {
    const update = readRepo("skills/update/SKILL.md");

    expect(update).toContain("플러그인: vX -> vY 받음 (재시작 필요)");
    expect(update).toContain("Claude Code 를 재시작하면 새 버전이 적용돼요.");
    expect(update).toContain("확인·비교 결과를 설명하는 영어 디버그 문장이나 raw 확인 줄은 쓰지 않아요");
    for (const leakedPhrase of ["PLUGIN_UPDATED_VERSION", "matching plugin.latest", "Confirmed:", "Confirmed", "plugin.latest"]) {
      expect(update).not.toContain(leakedPhrase);
    }
  });

  test("continues mixed app-status requests after the update boundary", () => {
    const update = readRepo("skills/update/SKILL.md");
    const clarity = readRepo("skills/clarity/SKILL.md");
    const hooks = readRepo("hooks/hooks.json");
    const policy = readRepo("POLICY.md");
    const clarityFrontmatter = clarity.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? "";

    expect(update).toContain("버전 확인과 다른 axhub 운영 요청을 함께 말하면");
    expect(update).toContain("버전 확인/업데이트 결과를 먼저");
    expect(update).toContain("업데이트 확인은 끝났어요. 이어서 요청하신 작업을 계속할게요.");
    expect(update).toContain("`App list (axhub)`, `Deployment list (axhub)`, `Tenant recent deployments (axhub)`, `App get (axhub)`");
    expect(update).toContain("read 작업이어도 CLI 계약을 우선해요");
    expect(update).toContain("원문이 영어로 `then`, `and then`, `after that`, `help me understand` 를 써도");
    expect(update).toContain("업데이트 뒤 남은 요청을 버리지 않아요");
    expect(update).toContain("CRITICAL post-update app overview");
    expect(update).toContain("`업데이트 확인은 끝났어요. 이어서 요청하신 앱 상태 확인을 계속할게요.` 를 말한 뒤에는 설치 확인·버전 확인·플러그인 확인을 다시 하지 않아요");
    expect(update).toContain("`command -v axhub`, `axhub --version`, `command -v claude`, `claude plugin list` 를 다시 실행하지 않아요");
    expect(update).toContain("`axhub apps --help`");
    expect(update).toContain("`axhub apps list --json`");
    expect(update).toContain("첫 overview 의 Desktop-visible Bash command 는 아래 두 개만 허용해요");
    expect(hooks).toContain("For plugin version lookup, the visible command is exactly claude plugin list; never claude plugin list 2>&1");
    expect(update).toContain("현재 폴더명·대화 맥락·가장 최근 수정 앱 중 하나로 관련 앱을 식별했으면");
    expect(update).toContain("멈춰서 \"어느 앱을 더 볼까요?\"라고 묻지 않아요");
    expect(update).toContain("상세와 최근 배포 이력까지 같은 흐름에서 바로 확인해요");
    expect(update).toContain("관련 앱을 하나로 좁혔는데 `이 중 어느 앱의 배포 상태나 로그를 더 자세히 확인하고 싶으신가요?`");
    expect(update).toContain("`어느 앱을 볼까요?`");
    expect(update).toContain("`더 자세히 확인하고 싶은 앱을 말해 주세요` 같은 질문으로 끝나면 실패예요");
    expect(update).toContain("`axhub apps get <app> --json`");
    expect(update).toContain("`axhub deploy list --app <app> --json`");
    expect(update).toContain("`Deployment list (axhub)`, `App get (axhub)`, `Tenant recent deployments (axhub)`");
    expect(update).toContain("존재하지 않는 `axhub deployment list`");
    expect(update).toContain("업데이트 결과 카드 뒤에는 남은 요청을 이어서 처리하되, 이때도 앱 상태/배포 이력은 MCP/App 도구가 아니라 위의 CLI overview 흐름으로 실행해요");
    expect(update).toContain("명령 문자열 뒤에 공백 외 어떤 문자도 붙이지 않아요");
    expect(update).toContain("존재하지 않는 단수 명령 `axhub app list`");
    expect(update).toContain("`command -v axhub && axhub --version`");
    expect(update).toContain("`command -v claude && claude plugin list`");
    expect(update).toContain("`claude plugin list 2>&1 | grep`");
    expect(update).toContain("`axhub apps list --json 2>/dev/null | head -100`");
    expect(update).toContain("`axhub --help | head`");
    expect(update).toContain("`&&`");
    expect(update).toContain("`2>/dev/null`");
    expect(update).toContain("`bash -lc`");
    expect(update).toContain("사용자의 추가 프롬프트를 기다리지 말고 다음 적절한 axhub 흐름을 시작해요");
    expect(update).toContain("`앱 상태 조회`, `배포 상태 조회`, `최근 배포 조회` 같은 tool 제목이 떠올랐다면");
    expect(update).toContain("Task/Subagent/Agent/백그라운드 작업으로 우회하지 않아요");
    expect(update).toContain("NEVER Task/Subagent/Agent/백그라운드 작업으로 mixed request 의 남은 앱 상태 확인을 우회하지 말아요");
    expect(update).toContain("update 결과 뒤 같은 assistant 흐름에서 직접 이어가요");
    expect(update).toContain("사용자가 `앱 상태 확인해줘`, `배포해줘`, `새 앱 만들어줘` 같은 말을 다시 하지 않아도 돼요");
    expect(update).toContain("바로 다음 axhub 흐름으로 이어가요");
    expect(update).not.toContain("다음 동작은 `clarity`");
    expect(update).not.toContain("그 다음 작업은 `clarity`");
    expect(clarity).toContain('Use this skill only for explicit "axhub clarity" requests');
    expect(clarityFrontmatter).toContain("disable-model-invocation: true");
    expect(clarity).toContain("사용자 수동 slash 또는 명시적 지목 때만 실행해요");
    expect(clarity).toContain("## Do not invoke / route guard");
    expect(clarity).toContain("첫 visible assistant text 를 정확히 `현재 버전을 확인할게요.`");
    expect(clarity).toContain("이미 `/axhub:clarity` 배지가 뜬 뒤 이 문서를 읽었다면");
    expect(clarity).toContain("`Using /axhub:clarity...` 같은 문장을 쓰거나 명령을 실행하지 말고");
    expect(clarity).toContain("내 앱들이 지금 어떤 상태인지도 알아서 봐줘");
    expect(clarity).toContain("`command -v axhub && axhub --version`");
    expect(clarity).toContain("`Checking axhub CLI installation and version`");
    expect(clarity).toContain("`MCP tools to check axhub status and your apps`");
    expect(clarityFrontmatter).toContain("app status overview");
    expect(clarityFrontmatter).toContain("app creation");
    expect(clarityFrontmatter).toContain("mixed freshness+status+create prompts");
    expect(clarityFrontmatter).toContain("최신/버전/update/latest/freshness checks");
    expect(clarityFrontmatter).toContain("GitHub 계정 재연결/device code");
    expect(clarity).not.toContain("내 앱들이 지금 어떤 상태인지 모르겠어");
    expect(clarityFrontmatter).not.toContain("내 앱들이 지금 어떤 상태인지도 알아서 봐줘");
    expect(clarity).not.toContain("operational-lookups.md");
    expect(clarity).not.toContain("show a read-only axhub overview");
    expect(clarity).not.toContain("is production healthy?");
    expect(hooks).toContain("UserPromptSubmit");
    expect(hooks).toContain("SessionStart");
    expect(hooks).toContain("AXHUB_NO_UPDATE_ROUTER");
    expect(hooks).toContain("axhub freshness/update");
    expect(hooks).toContain("hookSpecificOutput");
    expect(hooks).toContain("additionalContext");
    expect(hooks).toContain("Before Finding tools");
    expect(hooks).toContain("invoke the axhub update skill");
    expect(hooks).toContain("현재 버전을 확인할게요");
    expect(hooks).toContain("allowed visible commands are exactly axhub apps --help then axhub apps list --json");
    expect(hooks).toContain("Once the assistant says 업데이트 확인은 끝났어요");
    expect(hooks).toContain("must not run command-v, axhub --version, claude plugin list, plugin-location checks, or version probes again");
    expect(hooks).toContain("If folder/current conversation/latest list clearly identifies a related app, do not ask which app");
    expect(hooks).toContain("continue with CLI-only axhub apps get <app> --json and axhub deploy list --app <app> --json before any summary");
    expect(hooks).toContain("Never call Claude Desktop axhub App/MCP tools such as Deployment list (axhub), App get (axhub), or Tenant recent deployments (axhub)");
    expect(hooks).toContain("Never run nonexistent singular axhub app list");
    expect(hooks).toContain("Never run command -v axhub && axhub --version");
    expect(hooks).toContain("command -v claude && claude plugin list");
    expect(hooks).toContain("claude plugin list 2>&1 | grep");
    expect(hooks).toContain("axhub deployment list");
    expect(hooks).toContain("axhub apps --help");
    expect(hooks).toContain("axhub apps list --json");
    expect(hooks).toContain("Never add &&, pipes, redirects");
    expect(hooks).toContain("Never add &&, pipes, redirects, head, tail, grep, sed, awk, bash -lc, sh -c, or 2>/dev/null");
    expect(hooks).toContain("update-first routing guard is active for Code mode");
    expect(hooks).not.toContain("axhub update check --plugin-version");
    expect(policy).toContain('"axhub가 진짜 최신인지 먼저 확인"');
    expect(policy).toContain("가장 먼저 `update` 스킬로 처리해요");
    expect(policy).toContain("`/axhub:clarity`, `/oh-my-claudecode:autopilot` 를 먼저 실행하지 않아요");
    expect(policy).toContain("Code-mode update router guard");
    expect(policy).toContain("SessionStart fallback");
    expect(policy).toContain("UserPromptSubmit match");
    expect(policy).toContain("존재하지 않는 `axhub app list`");
    expect(policy).toContain("plural `axhub apps` 표면");
    expect(policy).toContain("이 앱 상태 흐름에 들어간 뒤에는 `command -v axhub && axhub --version`, `command -v claude && claude plugin list`, `claude plugin list 2>&1 | grep` 같은 설치·버전·플러그인 probe 를 다시 실행하지 않아요");
    expect(policy).toContain("현재 폴더명·대화 맥락·가장 최근 목록으로 관련 앱이 하나로 좁혀지면");
    expect(policy).toContain("사용자에게 어느 앱을 볼지 묻지 말고");
    expect(policy).toContain("`axhub apps get <app> --json`, `axhub deploy list --app <app> --json`");
    expect(policy).toContain("존재하지 않는 `axhub deployment list`");
    expect(policy).toContain("`Tenant recent deployments`, `Deployment list`, `App list`, `App get`");
    expect(policy).toContain("`| head`, `2>/dev/null`, `grep`, `&&` 같은 shell 후처리는 붙이지 않아요");
  });
});
