#!/usr/bin/env bun
/**
 * Phase 3 US-202: Catalog → Markdown codegen.
 *
 * Reads src/axhub-helpers/catalog.ts CATALOG and produces a canonical
 * markdown snapshot at skills/deploy/references/error-empathy-catalog.generated.md.
 *
 * The hand-written `error-empathy-catalog.md` is preserved as the skill-writer
 * reference (richer placeholders for runtime interpolation). The generated
 * file is the runtime fallback snapshot — what users actually see when no
 * interpolation context is available.
 *
 * Drift detection lives in tests/codegen.test.ts: every catalog.ts entry must
 * have a matching `## exit N` heading in the hand-written markdown.
 *
 * Idempotency: running this script twice produces an identical file (no diff).
 */
import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { CATALOG, type ErrorEntry } from "../src/axhub-helpers/catalog";

const REPO_ROOT = join(import.meta.dir, "..");
const OUTPUT = join(REPO_ROOT, "skills/deploy/references/error-empathy-catalog.generated.md");

const HEADER = `<!-- AUTO-GENERATED by scripts/codegen-catalog.ts. Edit catalog.ts then re-run. -->

# Error Empathy Catalog (Runtime Snapshot)

Auto-generated from \`src/axhub-helpers/catalog.ts\` CATALOG. This is the
runtime fallback — what \`classify-exit\` emits when no skill-side
interpolation context (app slug, deploy id, etc.) is available.

For the rich skill-writer template (with placeholder hints like
\`<APP_SLUG>\`, \`<DEPLOY_ID>\`, \`<RETRY_AFTER>\`), see the hand-written
\`error-empathy-catalog.md\` in this directory.

The drift between this file and the hand-written sibling is checked by
\`tests/codegen.test.ts\` — both must cover the same exit-code keys.

`;

const formatEntry = (key: string, entry: ErrorEntry): string => {
  // Key is either "<exit_code>" or "<exit_code>:<error_code>"
  const isSubClassified = key.includes(":");
  const heading = isSubClassified ? `### exit ${key}` : `## exit ${key}`;

  let body = `${heading}\n\n`;
  body += `**감정:** ${entry.emotion}\n\n`;
  body += `**원인:** ${entry.cause}\n\n`;
  body += `**해결:** ${entry.action}\n\n`;
  if (entry.button !== undefined) {
    body += `**버튼:** ${entry.button}\n\n`;
  }
  body += `---\n\n`;
  return body;
};

// Sort entries: base codes first (numeric), then sub-classified entries grouped
// under their parent code.
const sortKeys = (keys: string[]): string[] => {
  const baseKey = (k: string): number => parseInt(k.split(":")[0]!, 10);
  return [...keys].sort((a, b) => {
    const ba = baseKey(a);
    const bb = baseKey(b);
    if (ba !== bb) return ba - bb;
    // Same base: bare key first, sub-classified after (alphabetic by error_code).
    const subA = a.split(":")[1] ?? "";
    const subB = b.split(":")[1] ?? "";
    return subA.localeCompare(subB);
  });
};

const main = async (): Promise<void> => {
  const keys = sortKeys(Object.keys(CATALOG));
  let body = HEADER;
  for (const key of keys) {
    const entry = CATALOG[key];
    if (!entry) continue;
    body += formatEntry(key, entry);
  }
  await writeFile(OUTPUT, body);
  process.stdout.write(`codegen-catalog: wrote ${keys.length} entries → ${OUTPUT.replace(REPO_ROOT + "/", "")}\n`);
};

if (import.meta.main) {
  await main();
}

export { formatEntry, sortKeys };
