#!/usr/bin/env bun
/**
 * Catalog → Markdown codegen.
 *
 * Reads crates/axhub-helpers/data/catalog.json (Rust source-of-truth) and
 * produces the canonical markdown snapshot at
 * skills/deploy/references/error-empathy-catalog.generated.md.
 *
 * Drift detection lives in tests/codegen.test.ts: every catalog entry must
 * have a matching `## exit N` heading in the hand-written markdown.
 *
 * Idempotency: running this script twice produces an identical file (no diff).
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

interface ErrorEntry {
  emotion: string;
  cause: string;
  action: string;
  button?: string;
}

type Catalog = Record<string, ErrorEntry>;

const REPO_ROOT = join(import.meta.dir, "..");
const CATALOG_JSON = join(REPO_ROOT, "crates/axhub-helpers/data/catalog.json");
const OUTPUT = join(REPO_ROOT, "skills/deploy/references/error-empathy-catalog.generated.md");

const HEADER = `<!-- AUTO-GENERATED by scripts/codegen-catalog.ts. Edit crates/axhub-helpers/data/catalog.json then re-run. -->

# Error Empathy Catalog (Runtime Snapshot)

Auto-generated from \`crates/axhub-helpers/data/catalog.json\` (Rust source-of-truth).
Runtime fallback — what \`classify-exit\` emits when no skill-side
interpolation context (app slug, deploy id, etc.) is available.

For the rich skill-writer template (with placeholder hints like
\`<APP_SLUG>\`, \`<DEPLOY_ID>\`, \`<RETRY_AFTER>\`), see the hand-written
\`error-empathy-catalog.md\` in this directory.

The drift between this file and the hand-written sibling is checked by
\`tests/codegen.test.ts\` — both must cover the same exit-code keys.

`;

const formatEntry = (key: string, entry: ErrorEntry): string => {
  const isSubClassified = key.includes(":");
  const heading = isSubClassified ? `### exit ${key}` : `## exit ${key}`;

  let body = `${heading}\n\n`;
  body += `**감정:** ${entry.emotion}\n\n`;
  body += `**원인:** ${entry.cause}\n\n`;
  body += `**해결:** ${entry.action}\n\n`;
  if (entry.button !== undefined) {
    body += `**버튼:** ${entry.button}\n\n`;
  }
  body += `---\n\n`;
  return body;
};

const sortKeys = (keys: string[]): string[] => {
  const baseKey = (k: string): number => parseInt(k.split(":")[0]!, 10);
  return [...keys].sort((a, b) => {
    const ba = baseKey(a);
    const bb = baseKey(b);
    if (ba !== bb) return ba - bb;
    const subA = a.split(":")[1] ?? "";
    const subB = b.split(":")[1] ?? "";
    return subA.localeCompare(subB);
  });
};

const main = async (): Promise<void> => {
  const json = await readFile(CATALOG_JSON, "utf8");
  const catalog = JSON.parse(json) as Catalog;
  const keys = sortKeys(Object.keys(catalog));
  let body = HEADER;
  for (const key of keys) {
    const entry = catalog[key];
    if (!entry) continue;
    body += formatEntry(key, entry);
  }
  await writeFile(OUTPUT, body);
  process.stdout.write(`codegen-catalog: wrote ${keys.length} entries → ${OUTPUT.replace(REPO_ROOT + "/", "")}\n`);
};

if (import.meta.main) {
  await main();
}

export { formatEntry, sortKeys };
